# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyboard_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='keyboard_message.proto',
  package='pcbook',
  syntax='proto3',
  serialized_options=b'Z\t./;pcbook',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16keyboard_message.proto\x12\x06pcbook\"\x7f\n\x08Keyboard\x12\'\n\x06layout\x18\x01 \x01(\x0e\x32\x17.pcbook.Keyboard.Layout\x12\x0f\n\x07\x62\x61\x63klit\x18\x02 \x01(\x08\"9\n\x06Layout\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06QEERTY\x10\x01\x12\n\n\x06QWERTZ\x10\x02\x12\n\n\x06\x41ZERTY\x10\x03\x42\x0bZ\t./;pcbookb\x06proto3'
)



_KEYBOARD_LAYOUT = _descriptor.EnumDescriptor(
  name='Layout',
  full_name='pcbook.Keyboard.Layout',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='QEERTY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='QWERTZ', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AZERTY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=104,
  serialized_end=161,
)
_sym_db.RegisterEnumDescriptor(_KEYBOARD_LAYOUT)


_KEYBOARD = _descriptor.Descriptor(
  name='Keyboard',
  full_name='pcbook.Keyboard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='layout', full_name='pcbook.Keyboard.layout', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='backlit', full_name='pcbook.Keyboard.backlit', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _KEYBOARD_LAYOUT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=161,
)

_KEYBOARD.fields_by_name['layout'].enum_type = _KEYBOARD_LAYOUT
_KEYBOARD_LAYOUT.containing_type = _KEYBOARD
DESCRIPTOR.message_types_by_name['Keyboard'] = _KEYBOARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Keyboard = _reflection.GeneratedProtocolMessageType('Keyboard', (_message.Message,), {
  'DESCRIPTOR' : _KEYBOARD,
  '__module__' : 'keyboard_message_pb2'
  # @@protoc_insertion_point(class_scope:pcbook.Keyboard)
  })
_sym_db.RegisterMessage(Keyboard)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
