# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: memory_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='memory_message.proto',
  package='pcbook',
  syntax='proto3',
  serialized_options=b'Z\t./;pcbook',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14memory_message.proto\x12\x06pcbook\"\x9a\x01\n\x06Memory\x12\r\n\x05value\x18\x01 \x01(\x04\x12!\n\x04unit\x18\x02 \x01(\x0e\x32\x13.pcbook.Memory.Unit\"^\n\x04Unit\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03\x42IT\x10\x01\x12\x08\n\x04\x42YTE\x10\x02\x12\x0c\n\x08KILOBYTE\x10\x03\x12\x0c\n\x08MEGABYTE\x10\x04\x12\x0c\n\x08GIGABYTE\x10\x05\x12\x0c\n\x08TERABYTE\x10\x06\x42\x0bZ\t./;pcbookb\x06proto3'
)



_MEMORY_UNIT = _descriptor.EnumDescriptor(
  name='Unit',
  full_name='pcbook.Memory.Unit',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BIT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BYTE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KILOBYTE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEGABYTE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GIGABYTE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TERABYTE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=93,
  serialized_end=187,
)
_sym_db.RegisterEnumDescriptor(_MEMORY_UNIT)


_MEMORY = _descriptor.Descriptor(
  name='Memory',
  full_name='pcbook.Memory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='pcbook.Memory.value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit', full_name='pcbook.Memory.unit', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MEMORY_UNIT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=187,
)

_MEMORY.fields_by_name['unit'].enum_type = _MEMORY_UNIT
_MEMORY_UNIT.containing_type = _MEMORY
DESCRIPTOR.message_types_by_name['Memory'] = _MEMORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Memory = _reflection.GeneratedProtocolMessageType('Memory', (_message.Message,), {
  'DESCRIPTOR' : _MEMORY,
  '__module__' : 'memory_message_pb2'
  # @@protoc_insertion_point(class_scope:pcbook.Memory)
  })
_sym_db.RegisterMessage(Memory)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
